export const INDIAN_CITIES = [
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Delhi", state: "Delhi" },
  { city: "Bangalore", state: "Karnataka" },
  { city: "Hyderabad", state: "Telangana" },
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Kolkata", state: "West Bengal" },
  { city: "Surat", state: "Gujarat" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Pimpri-Chinchwad", state: "Maharashtra" },
  { city: "Patna", state: "Bihar" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Ludhiana", state: "Punjab" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Faridabad", state: "Haryana" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Kalyan-Dombivali", state: "Maharashtra" },
  { city: "Vasai-Virar", state: "Maharashtra" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Srinagar", state: "Jammu and Kashmir" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Navi Mumbai", state: "Maharashtra" },
  { city: "Allahabad", state: "Uttar Pradesh" },
  { city: "Howrah", state: "West Bengal" },
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Guwahati", state: "Assam" },
  { city: "Chandigarh", state: "Chandigarh" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Hubli-Dharwad", state: "Karnataka" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Mysore", state: "Karnataka" },
  { city: "Gurgaon", state: "Haryana" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Mira-Bhayandar", state: "Maharashtra" },
  { city: "Warangal", state: "Telangana" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Bhiwandi", state: "Maharashtra" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Gorakhpur", state: "Uttar Pradesh" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Amravati", state: "Maharashtra" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Bhilai", state: "Chhattisgarh" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Firozabad", state: "Uttar Pradesh" },
  { city: "Kochi", state: "Kerala" },
  { city: "Bhavnagar", state: "Gujarat" },
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "Asansol", state: "West Bengal" },
  { city: "Nanded", state: "Maharashtra" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Gulbarga", state: "Karnataka" },
  { city: "Jamnagar", state: "Gujarat" },
  { city: "Ujjain", state: "Madhya Pradesh" },
  { city: "Loni", state: "Uttar Pradesh" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Jhansi", state: "Uttar Pradesh" },
  { city: "Ulhasnagar", state: "Maharashtra" },
  { city: "Nellore", state: "Andhra Pradesh" },
  { city: "Jammu", state: "Jammu and Kashmir" },
  { city: "Sangli-Miraj & Kupwad", state: "Maharashtra" },
  { city: "Belgaum", state: "Karnataka" },
  { city: "Mangalore", state: "Karnataka" },
  { city: "Ambattur", state: "Tamil Nadu" },
  { city: "Tirunelveli", state: "Tamil Nadu" },
  { city: "Malegaon", state: "Maharashtra" },
  { city: "Gaya", state: "Bihar" },
  { city: "Jalgaon", state: "Maharashtra" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Maheshtala", state: "West Bengal" },
  { city: "Tirupur", state: "Tamil Nadu" },
  { city: "Davanagere", state: "Karnataka" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Akola", state: "Maharashtra" },
  { city: "Kurnool", state: "Andhra Pradesh" },
  { city: "Rajpur Sonarpur", state: "West Bengal" },
  { city: "Rajahmundry", state: "Andhra Pradesh" },
  { city: "Bokaro", state: "Jharkhand" },
  { city: "South Dumdum", state: "West Bengal" },
  { city: "Bellary", state: "Karnataka" },
  { city: "Patiala", state: "Punjab" },
  { city: "Gopalpur", state: "West Bengal" },
  { city: "Agartala", state: "Tripura" },
  { city: "Bhagalpur", state: "Bihar" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Bhatpara", state: "West Bengal" },
  { city: "Panihati", state: "West Bengal" },
  { city: "Latur", state: "Maharashtra" },
  { city: "Dhule", state: "Maharashtra" },
  { city: "Tirupati", state: "Andhra Pradesh" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Korba", state: "Chhattisgarh" },
  { city: "Bhilwara", state: "Rajasthan" },
  { city: "Berhampur", state: "Odisha" },
  { city: "Muzaffarpur", state: "Bihar" },
  { city: "Ahmednagar", state: "Maharashtra" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Gandhidham", state: "Gujarat" }
];
